version: '3.7'

networks:
  palswalk-common-network:
    external: true

volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local

services:
  # App Service
  app:
    depends_on:
      - mongodb
      - redis
    ports:
      - ${APP_BASE_HTTP_PORT}:3006
    volumes:
      - ./../src:/var/www
    networks:
      - palswalk-common-network

  #MongoDB
  mongodb:
    restart: unless-stopped
    container_name: palswalk-book-service-mongodb
    image: mongo:3.6
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongodata:/data/db
  
  # redis service
  redis:
    image: redis:6.2.7-alpine
    container_name: palswalk-book-redis
    restart: unless-stopped
    tty: true
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_HOST_BIND_PORT}:6379
    volumes:
      - redisdata:/data
    networks:
      - app-network
      - palswalk-common-network

