version: '3.7'

volumes:
  mongodata:
    driver: local
  redisdata:
    driver: local

services:
  # App Service
  app:
    depends_on:
      - mongodb
      - redis
    ports:
      - ${APP_BASE_HTTP_PORT}:3006
    volumes:
      - ./../src:/var/www


  #MongoDB
  mongodb:
    restart: unless-stopped
    container_name: bulkEmailSender-mongodb
    image: mongo:3.6
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "${MONGO_DB_PORT}:27017"
    volumes:
      - mongodata:/data/db
  
  # redis service
  redis:
    image: redis:6.2.7-alpine
    container_name: bulkEmailSender-redis
    restart: unless-stopped
    tty: true
    command: redis-server
    ports:
      - ${REDIS_HOST_BIND_PORT}:6379
    volumes:
      - redisdata:/data

